export const F = "'Helvetica Neue', Helvetica, Arial, sans-serif";

export const HOURS = [
  "09:00","10:00","11:00","12:00","13:00","14:00",
  "15:00","16:00","17:00","18:00","19:00",
];

export const STYLE_URL = "/tiles/styles/bright";
export const TILE_ORIGIN = "https://tiles.openfreemap.org/";

export const METRO_STATIONS = [
  "Abbesses","Alésia","Alexandre Dumas","Alma-Marceau","Anvers","Argentine",
  "Arts et Métiers","Assemblée Nationale","Avenue Émile Zola","Avron",
  "Balard","Barbès-Rochechouart","Bastille","Bel-Air","Belleville","Bercy",
  "Bibliothèque François Mitterrand","Bir-Hakeim","Blanche","Boissière","Bolivar",
  "Bonne Nouvelle","Botzaris","Boucicaut","Bourse","Bréguet-Sabin","Brochant",
  "Buttes Chaumont","Buzenval",
  "Cadet","Cambronne","Campo-Formio","Cardinal Lemoine","Censier-Daubenton",
  "Champs-Élysées - Clemenceau","Chardon-Lagache","Charles de Gaulle - Étoile",
  "Charles Michels","Charonne","Château d'Eau","Château-Landon","Château Rouge",
  "Châtelet","Chaussée d'Antin - La Fayette","Chemin Vert","Chevaleret","Cité",
  "Cluny-La Sorbonne","Colonel Fabien","Commerce","Concorde","Convention",
  "Corentin Cariou","Corvisart","Cour Saint-Émilion","Couronnes","Courcelles",
  "Crimée",
  "Danube","Daumesnil","Denfert-Rochereau","Dugommier","Dupleix","Duroc",
  "École Militaire","Edgar Quinet","Église d'Auteuil","Étienne Marcel","Europe","Exelmans",
  "Faidherbe-Chaligny","Falguière","Félix Faure","Filles du Calvaire",
  "Franklin D. Roosevelt",
  "Gaîté","Gambetta","Gare d'Austerlitz","Gare de l'Est","Gare de Lyon",
  "Gare du Nord","George V","Glacière","Goncourt","Grands Boulevards",
  "Guy Môquet",
  "Havre-Caumartin","Hôtel de Ville",
  "Iéna","Invalides",
  "Jacques Bonsergent","Jasmin","Jaurès","Javel-André Citroën","Jourdain",
  "Jules Joffrin","Jussieu",
  "Kléber",
  "La Chapelle","La Fourche","La Motte-Picquet-Grenelle","La Muette",
  "La Tour-Maubourg","Lamarck-Caulaincourt","Laumière","Le Peletier",
  "Ledru-Rollin","Les Gobelins","Liège","Louis Blanc","Lourmel","Louvre - Rivoli",
  "Luxembourg",
  "Mabillon","Madeleine","Mairie du 18e","Maison Blanche","Maraîchers",
  "Marcadet-Poissonniers","Marx Dormoy","Maubert-Mutualité","Ménilmontant",
  "Michel-Ange-Auteuil","Michel-Ange-Molitor","Michel Bizot","Mirabeau",
  "Miromesnil","Monceau","Montgallet","Montparnasse-Bienvenüe","Mouton-Duvernet",
  "Nation","Nationale","Notre-Dame-de-Lorette","Notre-Dame-des-Champs",
  "Oberkampf","Odéon","Olympiades","Opéra","Ourcq",
  "Palais Royal - Musée du Louvre","Parmentier","Passy","Pasteur","Pelleport","Pereire",
  "Père Lachaise","Pernety","Philippe Auguste","Picpus","Pigalle",
  "Place d'Italie","Place de Clichy","Place des Fêtes","Place Monge","Plaisance",
  "Poissonnière","Pont Cardinet","Pont de l'Alma","Pont Marie","Pont Neuf",
  "Porte d'Auteuil","Porte d'Italie","Porte d'Ivry","Porte d'Orléans","Porte Dauphine",
  "Porte de Bagnolet","Porte de Champerret","Porte de Charenton","Porte de Choisy","Porte de Clichy",
  "Porte de Clignancourt","Porte de la Chapelle","Porte de la Villette",
  "Porte de Montreuil","Porte de Pantin","Porte de Saint-Cloud",
  "Porte de Saint-Ouen","Porte de Vanves","Porte de Versailles","Porte de Vincennes",
  "Porte des Lilas","Porte Dorée","Porte Maillot",
  "Pré-Saint-Gervais","Pyramides","Pyrénées",
  "Quai de la Gare","Quai de la Rapée","Quatre-Septembre",
  "Rambuteau","Ranelagh","Raspail","Réaumur-Sébastopol","Rennes","République",
  "Reuilly-Diderot","Richard-Lenoir","Richelieu-Drouot","Riquet","Rome",
  "Rue de la Pompe","Rue des Boulets","Rue du Bac","Rue Saint-Maur",
  "Saint-Ambroise","Saint-Augustin","Saint-Fargeau","Saint-François-Xavier",
  "Saint-Georges","Saint-Germain-des-Prés","Saint-Jacques","Saint-Lazare",
  "Saint-Marcel","Saint-Maur","Saint-Michel","Saint-Paul",
  "Saint-Philippe du Roule","Saint-Placide","Saint-Sébastien-Froissart",
  "Saint-Sulpice","Ségur","Sentier","Sèvres-Babylone","Sèvres-Lecourbe",
  "Simplon","Solférino","Stalingrad","Strasbourg-Saint-Denis","Sully - Morland",
  "Télégraphe","Temple","Ternes","Tolbiac","Trinité-d'Estienne d'Orves",
  "Trocadéro","Tuileries",
  "Vaneau","Varenne","Vaugirard","Vavin","Victor Hugo","Villiers","Wagram",
  "Volontaires","Voltaire",
].sort();

// Stations with coords for random KPI on home page
export const KPI_STATIONS: { name: string; lat: number; lon: number }[] = [
  { name: "Bastille", lat: 48.8533, lon: 2.3692 },
  { name: "République", lat: 48.8675, lon: 2.3637 },
  { name: "Oberkampf", lat: 48.8649, lon: 2.3681 },
  { name: "Ledru-Rollin", lat: 48.8515, lon: 2.3767 },
  { name: "Nation", lat: 48.8485, lon: 2.3960 },
  { name: "Reuilly-Diderot", lat: 48.8474, lon: 2.3866 },
  { name: "Dupleix", lat: 48.8505, lon: 2.2937 },
  { name: "Odéon", lat: 48.8522, lon: 2.3387 },
  { name: "Gambetta", lat: 48.8653, lon: 2.3985 },
  { name: "Place d'Italie", lat: 48.8312, lon: 2.3555 },
  { name: "Belleville", lat: 48.8720, lon: 2.3766 },
  { name: "Arts et Métiers", lat: 48.8653, lon: 2.3562 },
  { name: "Saint-Paul", lat: 48.8552, lon: 2.3612 },
  { name: "Père Lachaise", lat: 48.8625, lon: 2.3867 },
  { name: "Censier-Daubenton", lat: 48.8408, lon: 2.3519 },
  { name: "Voltaire", lat: 48.8578, lon: 2.3804 },
  { name: "Bercy", lat: 48.8401, lon: 2.3796 },
  { name: "Ménilmontant", lat: 48.8669, lon: 2.3834 },
];

export const PLACE_TYPE_KEYS: Record<string, string> = {
  restaurant: "placeType.restaurant",
  cafe: "placeType.cafe",
  autre: "placeType.autre",
};

export const STATUS_CONFIG: Record<string, { labelKey: string; color: string; icon: string }> = {
  soleil: { labelKey: "status.soleil", color: "#92400E", icon: "sun" },
  mitige: { labelKey: "status.mitige", color: "#78350F", icon: "sun" },
  couvert: { labelKey: "status.couvert", color: "#4B5563", icon: "shade" },
  ombre: { labelKey: "status.ombre", color: "#374151", icon: "shade" },
  ombre_batiment: { labelKey: "status.ombre_batiment", color: "#374151", icon: "shade" },
  nuit: { labelKey: "status.nuit", color: "#334155", icon: "shade" },
};
